const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
let soundOn=true,audio,activeGame=null,timer=null,score=0;
const info={route:{name:'ПУЛЬС СЕТИ',title:'Пульс сети',html:'<ol><li>Нажимайте на плитки, чтобы поворачивать сегменты сети.</li><li>Каждый ход меняет выбранную плитку и её соседей.</li><li>Зажгите все 16 узлов за 45 секунд. Победа даёт 160 очков с бонусом за время.</li></ol>'},memory:{name:'ЭХО СОЗВЕЗДИЙ',title:'Эхо созвездий',html:'<ol><li>Наблюдайте последовательность вспышек.</li><li>Повторите её, нажимая на звёзды в том же порядке.</li><li>Каждый раунд добавляет одну звезду. Ошибка завершает игру.</li></ol>'},rhythm:{name:'РИТМ-САД',title:'Ритм-сад',html:'<ol><li>Светящиеся ростки появляются в ритме музыки.</li><li>Нажимайте на них, пока они не исчезли.</li><li>За точное попадание — 10 очков. За серию начисляется бонус.</li></ol>'}};
function tone(freq=440,d=.12,type='sine'){if(!soundOn)return;audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function toggleSound(){soundOn=!soundOn;$$('.sound-toggle').forEach(b=>b.textContent=`Звук: ${soundOn?'вкл':'выкл'}`);tone(520)}
$$('.sound-toggle').forEach(b=>b.onclick=toggleSound);
const modal=$('#rulesModal');let pending='route';
function openRules(id){pending=id;$('#rulesTitle').textContent=info[id].title;$('#rulesText').innerHTML=info[id].html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
$$('[data-rules]').forEach(b=>b.onclick=()=>openRules(b.dataset.rules));$('.close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};$('.modal-play').onclick=()=>{modal.classList.remove('open');startGame(pending)};
$$('[data-game]').forEach(b=>b.onclick=()=>startGame(b.dataset.game));
function startGame(id){cleanup();activeGame=id;score=0;$('#score').textContent=0;$('.game-name').textContent=info[id].name;$('#best').textContent=localStorage.getItem('lumen-'+id)||0;$('#gameScreen').classList.add('open');$('#gameScreen').setAttribute('aria-hidden','false');setup(id)}
function cleanup(){clearInterval(timer);timer=null;$('#gameArea').innerHTML='';$('.game-message').classList.remove('hidden')}
$('.back').onclick=()=>{cleanup();$('#gameScreen').classList.remove('open')};
function message(title,text,button='Начать игру'){let m=$('#gameMessage');$('h2',m).textContent=title;$('p',m).textContent=text;$('.restart',m).textContent=button;m.classList.remove('hidden')}
$('.restart').onclick=()=>setup(activeGame,true);
function setScore(n){score=n;$('#score').textContent=n}
function finish(text){clearInterval(timer);timer=null;let best=Math.max(score,+(localStorage.getItem('lumen-'+activeGame)||0));localStorage.setItem('lumen-'+activeGame,best);$('#best').textContent=best;tone(220,.3,'sawtooth');message('Игра окончена',text,'Ещё раз')}
function countdown(seconds,onEnd){$('#secondaryLabel').textContent='ВРЕМЯ';$('#secondary').textContent=seconds;timer=setInterval(()=>{seconds--;$('#secondary').textContent=seconds;if(seconds<=0){clearInterval(timer);timer=null;onEnd()}},1000)}
function setup(id,go=false){clearInterval(timer);$('#gameArea').innerHTML='';if(id==='route')route(go);if(id==='memory')memory(go);if(id==='rhythm')rhythm(go)}
function route(go){$('#secondaryLabel').textContent='ВРЕМЯ';$('#secondary').textContent='45';let area=$('#gameArea'),grid=document.createElement('div');grid.className='route-grid';let state=Array.from({length:16},()=>Math.random()>.5);state.forEach((v,i)=>{let b=document.createElement('button');b.className='tile'+(v?' on':'');b.style.transform=`rotate(${[0,90,180,270][i%4]}deg)`;b.onclick=()=>{[i,i-1,i+1,i-4,i+4].filter(j=>j>=0&&j<16&&!(i%4===0&&j===i-1)&&!(i%4===3&&j===i+1)).forEach(j=>{state[j]=!state[j];grid.children[j].classList.toggle('on',state[j])});tone(260+i*14);if(state.every(Boolean)){setScore(160+(+$('#secondary').textContent)*4);clearInterval(timer);tone(720,.4);message('Сеть сияет!',`Ваш результат: ${score} очков`,'Новая сеть')}};grid.append(b)});area.append(grid);message('Пульс сети','Зажгите все узлы за 45 секунд');if(go){$('.game-message').classList.add('hidden');countdown(45,()=>finish(`Вы набрали ${score} очков`))}}
function memory(go){$('#secondaryLabel').textContent='РАУНД';$('#secondary').textContent='0';let area=$('#gameArea'),grid=document.createElement('div');grid.className='memory-grid';let seq=[],input=[],locked=true;for(let i=0;i<9;i++){let b=document.createElement('button');b.className='star-btn';b.textContent='✦';b.onclick=()=>{if(locked)return;tone(300+i*45);flash(i);input.push(i);let k=input.length-1;if(input[k]!==seq[k])return finish(`Вы добрались до ${seq.length} раунда`);if(input.length===seq.length){locked=true;setScore(score+seq.length*10);setTimeout(round,650)}};grid.append(b)}area.append(grid);function flash(i){grid.children[i].classList.add('lit');setTimeout(()=>grid.children[i].classList.remove('lit'),350)}function round(){input=[];seq.push(Math.floor(Math.random()*9));$('#secondary').textContent=seq.length;let k=0;locked=true;let iv=setInterval(()=>{flash(seq[k]);tone(350+seq[k]*45);k++;if(k===seq.length){clearInterval(iv);setTimeout(()=>locked=false,400)}},650)}message('Эхо созвездий','Смотрите внимательно и повторяйте световой узор');if(go){$('.game-message').classList.add('hidden');round()}}
function rhythm(go){$('#secondaryLabel').textContent='ВРЕМЯ';$('#secondary').textContent='30';let area=$('#gameArea'),field=document.createElement('div');field.className='rhythm-field';area.append(field);let streak=0;function spawn(){let b=document.createElement('button');b.className='bud';b.textContent='✦';b.style.left=10+Math.random()*80+'%';b.style.top=10+Math.random()*70+'%';let alive=true;b.onclick=()=>{if(!alive)return;alive=false;streak++;setScore(score+10+Math.min(streak,5)*2);tone(420+streak*25);b.remove()};field.append(b);setTimeout(()=>{if(alive){alive=false;streak=0;b.remove()}},850)}message('Ритм-сад','Ловите ростки в течение 30 секунд');if(go){$('.game-message').classList.add('hidden');countdown(30,()=>finish(`Сад принёс ${score} очков`));let beat=setInterval(()=>{if(!timer)return clearInterval(beat);tone(130,.07,'triangle');spawn()},700)}}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.remove('open');if($('#gameScreen').classList.contains('open'))$('.back').click()}});
