const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
let soundOn=true,audio,activeGame=null,score=0,level=0,locked=false,completedLevels=new Set();
const topics=[
 {name:'Transport',ru:'Транспорт',words:[['car','машина'],['bus','автобус'],['lorry','грузовик'],['train','поезд'],['helicopter','вертолёт'],['ship','корабль']]},
 {name:'Toys',ru:'Игрушки',words:[['bear','мишка'],['doll','кукла'],['kite','воздушный змей'],['ball','мяч'],['game','игра'],['bike','велосипед']]},
 {name:'Room',ru:'Комната',words:[['lamp','лампа'],['mat','коврик'],['sofa','диван'],['table','стол'],['armchair','кресло']]}
];
const numberLevels=[{name:'Numbers 1–10',values:[1,2,3,4,5,6,7,8,9,10]},{name:'Numbers 11–21',values:[11,12,13,14,15,16,17,18,19,20,21]},{name:'Tens',values:[10,20,30,40,50,60,70,80,90,100]}];
const numberWords={1:'one',2:'two',3:'three',4:'four',5:'five',6:'six',7:'seven',8:'eight',9:'nine',10:'ten',11:'eleven',12:'twelve',13:'thirteen',14:'fourteen',15:'fifteen',16:'sixteen',17:'seventeen',18:'eighteen',19:'nineteen',20:'twenty',21:'twenty-one',30:'thirty',40:'forty',50:'fifty',60:'sixty',70:'seventy',80:'eighty',90:'ninety',100:'one hundred'};
const info={match:{name:'WORD MATCH',title:'Word Match',html:'<ol><li>Выберите тему: транспорт, игрушки или комната.</li><li>Открывайте по две карточки и находите пару «английское слово — перевод».</li><li>В каждом уровне 5 пар. За завершённый уровень вы получите 5 баллов.</li></ol>'},sound:{name:'SOUND DETECTIVE',title:'Sound Detective',html:'<ol><li>Нажмите на динамик и внимательно послушайте число на английском.</li><li>Выберите услышанное число из четырёх вариантов.</li><li>Уровни: 1–10, 11–21 и десятки от 10 до 100. В каждом — 5 вопросов.</li></ol>'},unscramble:{name:'UNSCRAMBLE',title:'Unscramble',html:'<ol><li>Прочитайте перевод или послушайте слово.</li><li>Нажимайте на перемешанные буквы в правильном порядке.</li><li>Соберите 5 слов, чтобы пройти уровень. Ошибочную букву можно удалить.</li></ol>'}};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function tone(freq=440,d=.12,type='sine'){if(!soundOn)return;audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function speak(text){if(!soundOn)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.78;speechSynthesis.speak(u)}
function toggleSound(){soundOn=!soundOn;$$('.sound-toggle').forEach(b=>b.textContent=soundOn?'🔊 Sound':'🔇 Sound');tone(520)}
$$('.sound-toggle').forEach(b=>b.onclick=toggleSound);
$$('[data-game]').forEach(b=>b.onclick=()=>startGame(b.dataset.game));
function startGame(id){activeGame=id;score=0;level=0;completedLevels=new Set();$('#score').textContent=0;$('.game-name').textContent=info[id].name;$('#best').textContent=localStorage.getItem('lumen-'+id)||0;$('#secondaryLabel').textContent='LEVEL';$('#secondary').textContent='1 / 3';$('#gameScreen').classList.add('open');coach("Let's play!");showIntro()}
function showIntro(){$('#gameArea').innerHTML='';let intro={match:['Match the pairs!','Open two cards. Find an English word and its Russian translation.'],sound:['Listen carefully!','Press the speaker, listen to the number and choose the correct answer.'],unscramble:['Spell the word!','Listen or read the hint, then press the letters in the correct order.']};message(intro[activeGame][0],intro[activeGame][1],'Choose a level')}
function goHome(){$('#gameScreen').classList.remove('open');speechSynthesis.cancel()}
$('.back').onclick=goHome;$('.message-home').onclick=goHome;
function message(title,text,button,finished=false){let m=$('#gameMessage');$('h2',m).textContent=title;$('p',m).textContent=text;$('.restart',m).textContent=button;$('.restart',m).dataset.action=finished?'replay':'levels';$('.message-home',m).style.display=finished?'inline-block':'none';m.classList.remove('hidden')}
function hideMessage(){$('#gameMessage').classList.add('hidden')}
$('.restart').onclick=e=>e.currentTarget.dataset.action==='replay'?startGame(activeGame):showLevelSelect();
function coach(text,good=true){let bubble=$('#jaySpeech');bubble.textContent=text;bubble.classList.toggle('try',!good)}
function setScore(n){score=n;$('#score').textContent=n}
function saveBest(){let best=Math.max(score,+(localStorage.getItem('lumen-'+activeGame)||0));localStorage.setItem('lumen-'+activeGame,best);$('#best').textContent=best}
function showLevelSelect(){hideMessage();let area=$('#gameArea');area.innerHTML='<div class="level-select"><p class="eyebrow">ВЫБЕРИТЕ УРОВЕНЬ</p><h2>С чего начнём?</h2><div class="level-buttons"></div></div>';let names=activeGame==='match'?topics.map(t=>`${t.name}<small>${t.ru}</small>`):activeGame==='sound'?numberLevels.map(t=>t.name):['Transport','Toys & Room','Numbers'];names.forEach((n,i)=>{let b=document.createElement('button');b.innerHTML=`<span>${completedLevels.has(i)?'✓':'0'+(i+1)}</span>${n}`;b.disabled=completedLevels.has(i);b.onclick=()=>beginLevel(i);$('.level-buttons',area).append(b)})}
function beginLevel(i){level=i;$('#secondary').textContent=`${i+1} / 3`;if(activeGame==='match')matchLevel();if(activeGame==='sound')soundLevel();if(activeGame==='unscramble')unscrambleLevel()}
function completeLevel(){if(!completedLevels.has(level)){completedLevels.add(level);setScore(score+5)}saveBest();tone(760,.35);coach('Amazing! You made Jay happy!');message('Great job!',`You earned 5 points. Score: ${score} / 15`,'Play again',true)}
function matchLevel(){hideMessage();locked=false;let area=$('#gameArea'),chosen=shuffle(topics[level].words).slice(0,5),cards=shuffle(chosen.flatMap((w,id)=>[{text:w[0],id,en:true},{text:w[1],id,en:false}]));area.innerHTML=`<div class="lesson-head"><span>ТЕМА</span><h2>${topics[level].name} <small>${topics[level].ru}</small></h2><p><b id="pairsLeft">5</b> пар осталось</p></div><div class="match-grid"></div>`;let first=null,found=0;cards.forEach(c=>{let b=document.createElement('button');b.className='match-card';b.dataset.id=c.id;b.innerHTML='<span>?</span>';b.onclick=()=>{if(locked||b.classList.contains('found')||b===first)return;b.classList.add('open');b.innerHTML=`<span>${c.text}</span><i>${c.en?'EN':'RU'}</i>`;if(c.en)speak(c.text);if(!first){first=b;return}if(first.dataset.id===b.dataset.id){b.classList.add('found');first.classList.add('found');first=null;found++;$('#pairsLeft').textContent=5-found;tone(620);if(found===5)setTimeout(completeLevel,600)}else{locked=true;tone(180);let prev=first;first=null;setTimeout(()=>{[prev,b].forEach(x=>{x.classList.remove('open');x.innerHTML='<span>?</span>'});locked=false},750)}};$('.match-grid',area).append(b)})}
function soundLevel(){hideMessage();let pool=numberLevels[level].values,questions=shuffle(pool).slice(0,5),q=0,area=$('#gameArea');function render(){let answer=questions[q],options=shuffle([answer,...shuffle(pool.filter(n=>n!==answer)).slice(0,3)]);area.innerHTML=`<div class="sound-game"><p class="eyebrow">ВОПРОС ${q+1} ИЗ 5</p><button class="speaker">🔊</button><h2>Какое число вы услышали?</h2><div class="answer-grid"></div><p class="feedback">Можно слушать несколько раз</p></div>`;$('.speaker',area).onclick=()=>speak(numberWords[answer]);options.forEach(n=>{let b=document.createElement('button');b.textContent=n;b.onclick=()=>{if(locked)return;locked=true;if(n===answer){b.classList.add('correct');$('.feedback',area).textContent=`Верно — ${numberWords[answer]}!`;tone(650)}else{b.classList.add('wrong');$('.feedback',area).textContent=`Ответ: ${answer} — ${numberWords[answer]}`;tone(170);$$('.answer-grid button',area).find(x=>+x.textContent===answer).classList.add('correct')}setTimeout(()=>{locked=false;q++;q<5?render():completeLevel()},1100)};$('.answer-grid',area).append(b)});setTimeout(()=>speak(numberWords[answer]),300)}render()}
function unscrambleLevel(){hideMessage();let sets=[topics[0].words,topics[1].words.concat(topics[2].words),Object.entries(numberWords).map(([n,w])=>[w,n])],words=shuffle(sets[level]).slice(0,5),q=0,area=$('#gameArea');function render(){let [word,hint]=words[q],target=word.replace(/[- ]/g,''),chars=shuffle(target.split('').map((char,id)=>({char,id}))),built=[];area.innerHTML=`<div class="unscramble"><p class="eyebrow">СЛОВО ${q+1} ИЗ 5</p><button class="listen-word">🔊 Прослушать</button><p class="word-hint">${level===2?'Число':'Перевод'}: <b>${hint}</b></p><div class="word-slots"></div><div class="letter-bank"></div><button class="erase">← Удалить букву</button><p class="feedback">Выберите буквы по порядку</p></div>`;let bank=$('.letter-bank',area),slots=$('.word-slots',area);$('.listen-word',area).onclick=()=>speak(word);chars.forEach(o=>{let b=document.createElement('button');b.textContent=o.char;b.onclick=()=>{b.disabled=true;built.push({char:o.char,button:b});slots.textContent=built.map(x=>x.char).join('');tone(380+built.length*20);if(built.length===target.length){if(slots.textContent===target){slots.classList.add('correct-word');$('.feedback',area).textContent='Верно!';speak(word);setTimeout(()=>{q++;q<5?render():completeLevel()},900)}else $('.feedback',area).textContent='Почти! Удалите неверные буквы.'}};bank.append(b)});$('.erase',area).onclick=()=>{let last=built.pop();if(last){last.button.disabled=false;slots.textContent=built.map(x=>x.char).join('');$('.feedback',area).textContent='Выберите буквы по порядку'}}}render()}
document.addEventListener('click',e=>{let card=e.target.closest('.match-card');if(card)setTimeout(()=>{if(card.classList.contains('found'))coach('Great match!');else if(!card.classList.contains('open'))coach('Try another card!',false)},800);let answer=e.target.closest('.answer-grid button');if(answer)setTimeout(()=>coach(answer.classList.contains('wrong')?'Good try! Listen again.':'Well done!',!answer.classList.contains('wrong')),40);let letter=e.target.closest('.letter-bank button');if(letter)setTimeout(()=>{let slots=$('.word-slots');if(slots?.classList.contains('correct-word'))coach('Perfect spelling!')},40)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#gameScreen').classList.contains('open'))goHome()});
